### ISSUE TITLE
Logos de empresa y juego

### ISSUE THREAD

**Issue by JAAmaya** [Poligonal-Knights/Arte#8]

**Comment by FelinexA10** [comment]
![Poligonal Knights Banner](https://user-images.githubusercontent.com/93128875/193478772-656bd812-512c-4488-8f85-8027fd16499d.png)
![Poligonal Knights Logo](https://user-images.githubusercontent.com/93128875/193478774-73ef41ef-e0b4-40ca-b497-0f35c67d71b4.png)
